version: 2
updates:
  # Root package.json
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
    labels:
      - "dependencies"
      - "npm"
    commit-message:
      prefix: "npm"
      include: "scope"
    ignore:
      - dependency-name: "next"
        update-types: ["version-update:semver-major"]

  # Home zone
  - package-ecosystem: "npm"
    directory: "/home"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
    labels:
      - "dependencies"
      - "npm"
      - "home"
    commit-message:
      prefix: "npm"
      include: "scope"
    ignore:
      - dependency-name: "next"
        update-types: ["version-update:semver-major"]

  # Catalog zone
  - package-ecosystem: "npm"
    directory: "/catalog"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
    labels:
      - "dependencies"
      - "npm"
      - "catalog"
    commit-message:
      prefix: "npm"
      include: "scope"
    ignore:
      - dependency-name: "next"
        update-types: ["version-update:semver-major"]

  # Account zone
  - package-ecosystem: "npm"
    directory: "/account"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
    labels:
      - "dependencies"
      - "npm"
      - "account"
    commit-message:
      prefix: "npm"
      include: "scope"
    ignore:
      - dependency-name: "next"
        update-types: ["version-update:semver-major"]

  # Shared package
  - package-ecosystem: "npm"
    directory: "/shared"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
    labels:
      - "dependencies"
      - "npm"
      - "shared"
    commit-message:
      prefix: "npm"
      include: "scope"
    ignore:
      - dependency-name: "next"
        update-types: ["version-update:semver-major"]

  # Docker dependencies
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
      - "docker"
    commit-message:
      prefix: "docker"
      include: "scope" 