name: Update Architecture Diagram

on:
  push:
    branches:
      - main
    paths:
      - '**/__tests__/architecture/**'
      - '**/src/**'
      - 'README.md'
      - '.github/workflows/architecture-diagram.yml'

permissions:
  contents: write

jobs:
  update-diagram:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Run architecture tests and generate diagram
        run: |
          # Run the diagram generation script
          node scripts/generate-architecture-diagram.js
          
          # Update README.md with the new diagram
          awk '
          BEGIN { p=1 }
          /^## Architecture Diagram/ { p=0; system("cat temp-diagram.md"); next }
          /^```mermaid/ { p=0; next }
          /^```$/ { p=1; next }
          p { print }
          ' README.md > README.md.new
          
          mv README.md.new README.md
          rm temp-diagram.md

      - name: Run ts-arch tests
        run: npm run test:architecture

      - name: Commit and push if changed
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          git add README.md
          git diff --quiet && git diff --staged --quiet || (git commit -m "Update architecture diagram" && git push) 