name: Update Architecture Constraints

on:
  push:
    branches:
      - main
    paths:
      - '**/__tests__/architecture/**'
      - '**/src/**'
      - 'README.md'
      - '.github/workflows/architecture-diagram.yml'

permissions:
  contents: write

jobs:
  update-architecture-constraints:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Generate architecture constraints section
        run: node scripts/generate-architecture-diagram.js

      - name: Update README.md with architecture constraints
        run: |
          awk '
          BEGIN { p=1 }
          /^## Architecture Constraints/ { p=0; system("cat temp-architecture-rules.md"); next }
          p { print }
          ' README.md > README.md.new
          mv README.md.new README.md
          rm temp-architecture-rules.md

      - name: Run ts-arch tests
        run: npm run test:architecture

      - name: Restore package-lock.json
        run: git restore package-lock.json

      - name: Commit and push if changed
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          git add README.md
          git diff --quiet && git diff --staged --quiet || (git commit -m "Update architecture constraints" && git push) 